sudo: false

branches:
  only:
    - master
    - /^\d+\.\d+\.x$/  # release forked patches branch.
    - /^\d+\.\d+\.\d+/ # tags format to we get releases pushed.

language: python
python:
  - 2.7

cache:
  directories:
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION.9
    - vendor/cache

matrix:
  fast_finish: true
  include:
    - os: osx
      language: generic
      python:
      env: TRAVIS_FLAVOR=default

env:
  global:
    - CONCURRENCY=2
    - NOSE_FILTER="not windows"
    - INTEGRATIONS_DIR=$HOME/embedded
    - CHECKSD_OVERRIDE=$TRAVIS_BUILD_DIR/tests/checks/fixtures/checks
    - PIP_CACHE=$HOME/.cache/pip
    - VOLATILE_DIR=/tmp
    - DD_CASHER_DIR=/tmp/casher
    - AGENT_VERSION=2.2.1
  matrix:
    - TRAVIS_FLAVOR=default
    - TRAVIS_FLAVOR=checks_mock

matrix:
  include:
    - python: 2.7
      sudo: required
      services: docker
      env: TRAVIS_FLAVOR=core_integration

# Override travis defaults with empty jobs
before_install:
- rvm install 2.1.5
# before_install: echo "OVERRIDING TRAVIS STEPS"
install: echo "OVERRIDING TRAVIS STEPS"
before_script: echo "OVERRIDING TRAVIS STEPS"

script:
  - ./.travis/build_installer.sh


after_failure:
  - echo "Logs from installation process come here / DEBUG LOGS"
  - cat /tmp/ci.log

notifications:
  slack:
    secure: N7WQuQNLn4wJqGHnLmTOZL18NGdr7vKNyHSV0TnXcgijnoqt+yxOq7mEu+h/KLgflAQObyKF8A3ChmbTB99xL6fR8xYVvxLSPk7+g9PU6Vf7absN9yY0rUQfXcPLVyYsZ11R1UqkizYbxc9B2A588S48/TMP2KB6LnII+PNajyg=

deploy:
  - provider: releases
    api_key:
      secure: "Z36hDHOTIfCHG3q6KTKsSA9V3S8QyRqgpZirR2RlWQinJx1xt9K3V8zIG4DheRNYxwB2z8K4tuyEX3JXLovKXfGSDsT7Tq2nfH7YRQlMP3jqNB8H7CzsTQlFdXM8lBXyalSamNVa/UdZZHHBDCQjk8ZKm/TlsBY626d6NdgXwWM="
    skip_cleanup: true
    file: sd-agent-$AGENT_VERSION.dmg
    on:
      tags: true
      condition: $TRAVIS_OS_NAME == osx
      repo: serverdensity/sd-agent
